#!/bin/bash

echo "🤖 Adding AI News Sources to Formul8 News Database"
echo ""
echo "This will add the following AI news sources:"
echo "  - OpenAI Blog"
echo "  - Anthropic News"
echo "  - Hugging Face Blog"
echo "  - Google AI Blog"
echo "  - The Batch by deeplearning.ai"
echo "  - AI News - MIT Technology Review"
echo "  - VentureBeat AI"
echo ""
echo "📝 To apply this migration:"
echo ""
echo "1. Open Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/gptfmaceymhubyuhqegu/sql/new"
echo ""
echo "2. Copy and paste the contents of:"
echo "   supabase/migrations/20260305180200_add_ai_sources.sql"
echo ""
echo "3. Click 'Run' to execute"
echo ""
echo "4. Deploy updated enrichment function:"
echo "   supabase functions deploy enrich-signals"
echo ""
echo "5. Test ingestion:"
echo "   curl -X POST 'https://gptfmaceymhubyuhqegu.supabase.co/functions/v1/ingest-orchestrator' \\"
echo "     -H 'Authorization: Bearer SERVICE_KEY' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"source_types\": [\"RSS\"]}'"
echo ""
